### ISSUE TITLE
Does not work with Next.js SSR or api routes

### ISSUE THREAD

**Issue by franzwilhelm** [segmentio/analytics-next#351]
When trying to use analytics-next on backend window is not defined. The source code that breaks the initialization lies here:
https://github.com/segmentio/analytics-next/blob/master/src/lib/priority-queue/persisted.ts#L112

Am I doing anything wrong?

```
ReferenceError: window is not defined
    at new PersistedPriorityQueue (/Users/franzvonderlippe/Programming/ally/node_modules/@segment/analytics-next/dist/cjs/lib/priority-queue/persisted.js:88:9)
    at new Analytics (/Users/franzvonderlippe/Programming/ally/node_modules/@segment/analytics-next/dist/cjs/analytics.js:36:97)
    at getServerSideProps (webpack-internal:///./pages/bookings/[id]/index.tsx:237:27)
    at Object.renderToHTML (/Users/franzvonderlippe/Programming/ally/node_modules/next/dist/server/render.js:479:26)
    at async doRender (/Users/franzvonderlippe/Programming/ally/node_modules/next/dist/server/next-server.js:1389:38)
    at async /Users/franzvonderlippe/Programming/ally/node_modules/next/dist/server/next-server.js:1484:28
    at async /Users/franzvonderlippe/Programming/ally/node_modules/next/dist/server/response-cache.js:63:36
    ```

**Comment by chrisradek** [comment]
@franzwilhelm Thanks for reporting this issue! For node.js applications, [AnalyticsNode](https://github.com/segmentio/analytics-next/blob/cc3982f132e74bea47c134b1133c716baccc7d02/src/node.ts#L9) uses a non-persistent priority queue and doesn't need to be ran in a browser environment.

It looks like this isn't currently being exported from the `cjs` bundle so we'll need to publish an update. Working on it and will post updates here!

**Comment by franzwilhelm** [comment]
@chrisradek Thanks a lot! Wrapped a lot around the segment library, so started to worry I did something wrong on my end. Will test with AnalyticsNode tomorrow morning!
