### ISSUE TITLE
AnalyticsBrowser - amplitude-plugins/sessionId - Unexpected token '.'

### ISSUE THREAD

**Issue by Jackman3005** [segmentio/analytics-next#734]
### The Issue
In our production environment Sentry is picking up an error when a user tries to fire an analytics event. (Out of the 10 Sentry events I analyzed all but one had the error occur right after the second analytics event is fired, ONE of them happened without the second event occurring at all)

### Stack Trace
Here's the Raw Stack Trace
```
SyntaxError: Unexpected token '.'
  at definition.actions.sessionId.perform(webpack://[name]Destination/./src/destinations/amplitude-plugins/sessionId/index.ts:60:23)
```

Sentry provides the following "pretty" stack trace. As noted in the stack trace above, the offending error occurs at position 60:23. Line 60 is the first line with the `if` statement, character 23 is the `.` between the first appearance of `event.integrations` in that line.
```
if (context.event.integrations?.All !== false || context.event.integrations['Actions Amplitude']) {
  context.updateEvent('integrations.Actions Amplitude', {})
  context.updateEvent('integrations.Actions Amplitude.session_id', id)
}
```

### More Context
It does not appear to be happening all the time, but it comes up regularly in our Sentry logs.

From what I can tell the order of events on our side is:
1 - User opens app - `Start App` analytics event is fired (no apparent issue with this)
2 - Segment GET request to `https://cdn.segment.com/v1/projects/{our-project-id}/settings` completes
3 - We fire an analytics event `Navigate to Screen` to record the initial screen they start on
4 - ???
5 - Error happens

I don't know for sure if the order is different than when it "works" but the error message in the stack does seem a bit strange.

__Has anyone else run into this yet?__

Thanks in advance,
Jack (& The Questmate Team)

**Comment by silesky** [comment]
@Jackman3005 related to https://github.com/segmentio/action-destinations/pull/943

**Comment by Jackman3005** [comment]
Ahh, nice. Yeah seems likely! I look forward to updating and testing when the PR is merged.

**Comment by Jackman3005** [comment]
Hey all 👋 I just wanted to confirm that we are still seeing this error. Here are the details for the latest reported error:

```
SyntaxError: Unexpected token .
  at s.actions.sessionId.perform(./destinations/amplitude-plugins/src/sessionId/index.ts:79:23)
```

- Chrome 101.0.4951
- Windows >= 10
- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36
- sentry.javascript.browser v7.7.0

**Comment by Jackman3005** [comment]
Hi @silesky it appears that [the PR](https://github.com/segmentio/action-destinations/pull/943) you linked to earlier in this thread has turned out to not be the best approach to solving this issue. Do you have some ideas of other options to explore that could resolve the issue?

Please let me know if there is some way I can help.

Cheers,
Jack

**Comment by silesky** [comment]
@Jackman3005 sorry -- the team responsible for that repo removed the issue queue, and there's been a lot of churn. I would create a formal support ticket and link to that GitHub issue. Basically, the issue is that action destinations are not transpiled for support for older browsers.

There is a new workaround on the latest ajs assuming you're installing segment:

https://github.com/segmentio/segment-docs/pull/5315/files

If you install:
@segment/analytics-browser-actions-amplitude

and pass it (see doc link), you can transpile it to es5 using your own build system (e.g webpack + babel)

**Comment by Jackman3005** [comment]
Hey @silesky thanks for the reply and insight. We are not in an enterprise environment and are hoping to avoid the ownership of the solution you suggested, but I do appreciate you bringing it up and potentially others may benefit from it.

I have created a Segment support ticket that should hopefully kick start things a bit and get a resolution to this soon.

Cheers!
Jack
