### ISSUE TITLE
Node: "window is not defined"

### ISSUE THREAD

**Issue by hatton** [segmentio/analytics-next#735]
Using 1.48.0 with this code in the main process of an Electron application:

```
import { Analytics, AnalyticsNode } from "@segment/analytics-next";
let analytics: Analytics | undefined;
export async function initializeAnalyticsMain() {
  const key = ...
  const [analytics, context] = await AnalyticsNode.load({ writeKey: key });
```

I get

```
(node:29264) UnhandledPromiseRejectionWarning: ReferenceError: window is not defined
    at module.exports../node_modules/@segment/analytics-next/dist/pkg/core/user/index.js.Cookie.available (C:\dev\lameta\app\main-bundle.js:5828:29)
    at getAvailableStorageOptions (C:\dev\lameta\app\main-bundle.js:6021:24)
    at new Analytics (C:\dev\lameta\app\main-bundle.js:3640:238)        
    at Function.<anonymous> (C:\dev\lameta\app\main-bundle.js:7125:37)  
    at step (C:\dev\lameta\app\main-bundle.js:8457:23)
```

Presumably `window` is never available in NodeJS. So am I calling something incorrectly?

**Comment by hatton** [comment]
I'm closing and will start again.
