### ISSUE TITLE
On load TypeError: f is not a function

### ISSUE THREAD

**Issue by pdeville-ledger** [segmentio/analytics-next#848]
With Next js It works perfectly fine with npm run dev

but When I build and run npm run start

I've got this error on the

 **AnalyticsBrowser.load({
          writeKey,
 })**

`522-35ab21ae09fb2866.js:3 Uncaught (in promise) TypeError: f is not a function
    at b._resolveLoadStart (522-35ab21ae09fb2866.js:3:912034)
    at b.load (522-35ab21ae09fb2866.js:3:912128)
    at b.load (522-35ab21ae09fb2866.js:3:912212)
    at referral-ll-c835145a339883e1.js:1:11417
    at u (main-7dd437265575797d.js:1:109984)
    at Generator._invoke (main-7dd437265575797d.js:1:111274)
    at a.<computed> [as next] (main-7dd437265575797d.js:1:110387)
    at ac (referral-ll-c835145a339883e1.js:1:10145)
    at d (referral-ll-c835145a339883e1.js:1:11646)
    at referral-ll-c835145a339883e1.js:1:11707`

**Comment by pdeville-ledger** [comment]
I was due to 
  swcMinify: true,

in next js config
